export const countriesData = [
  ["AL", "Albania"],
  ["DZ", "Algeria"],
  ["AQ", "Antarctica"],
  ["AR", "Argentina"],
  ["AM", "Armenia"],
  ["AU", "Australia"],
  ["AT", "Austria"],
  ["BS", "Bahamas"],
  ["BH", "Bahrain"],
  ["BE", "Belgium"],
  ["BR", "Brazil"],
  ["CM", "Cameroon"],
  ["CA", "Canada"],
  ["CN", "China"],
  ["CO", "Colombia"],
  ["CR", "Costa Rica"],
  ["CU", "Cuba"],
  ["DK", "Denmark"],
  ["EC", "Ecuador"],
  ["EG", "Egypt"],
  ["FI", "Finland"],
  ["FR", "France"],
  ["DE", "Germany"],
  ["GH", "Ghana"],
  ["HK", "Hong Kong"],
  ["HU", "Hungary"],
  ["IS", "Iceland"],
  ["IN", "India"],
  ["IE", "Ireland"],
  ["IL", "Israel"],
  ["IT", "Italy"],
  ["JM", "Jamaica"],
  ["JP", "Japan"],
  ["KE", "Kenya"],
  ["KP", "South Korea"],
  ["LU", "Luxembourg"],
  ["MX", "Mexico"],
  ["MA", "Morocco"],
  ["NL", "Netherlands"],
  ["NG", "Nigeria"],
  ["NO", "Norway"],
  ["PL", "Poland"],
  ["PT", "Portugal"],
  ["PR", "Puerto Rico"],
  ["QA", "Qatar"],
  ["RU", "Russia"],
  ["SM", "San Marino"],
  ["SA", "Saudi Arabia"],
  ["SN", "Senegal"],
  ["SG", "Singapore"],
  ["ZA", "South Africa"],
  ["ES", "Spain"],
  ["LK", "Sri Lanka"],
  ["TW", "Taiwan"],
  ["TH", "Thailand"],
  ["TG", "Togo"],
  ["TR", "Turkey"],
  ["UG", "Uganda"],
  ["UA", "Ukraine"],
  ["AE", "United Arab Emirates"],
  ["GB", "United Kingdom"],
  ["US", "United States"],
];
